### PR TITLE
Quota check for the routing feature

### PR DESCRIPTION
**Pull request by ethervoid**
- We have refactor all the quota logic and extracted to a new QuotaChecker class in order to have it ready to create a factory when needed
- Added the logic for the routing quota check

### CODE REVIEW

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
retest this please

**Comment by ethervoid** [comment]
Please @rafatower check this out :)))

**Comment by rafatower** [comment]
:+1:

**Pull request merged**
