### PR TITLE
Revert number of isochrone retries to 3

### PR DESCRIPTION
**Pull request by jgoizueta**
See #317 
Note that finally the number of retries has been set at 1 (see below)

### CODE REVIEW

**Comment by jgoizueta** [comment]
@rafatower  please review

**Comment by rafatower** [comment]
:+1:

**Comment by rafatower** [comment]
as commented in person: let's do the versioning stuff in the developmet branch

**Comment by rafatower** [comment]
:+1:

**Comment by jgoizueta** [comment]
It seems that we were passing the `MAX_RETRIES` parameter as the first argument to the requests' `HTTPAdapter` constructor, which is the connections pool size actually, so it wasn't having the intended effect and the default value of 0 retries was being used.

I've fixed the argument passing part (using a keyword parameter) here: https://github.com/CartoDB/dataservices-api/pull/320/commits/79fb7961802a15effdad772861d94350808793e7
but changing all our `MAX_RETRIES` constants to 0, so that we don't change current behaviour.

I think we should further discuss/test the effects of changing `MAX_RETRIES` since it will affect the effective time till a timeout exception is generated by the retries library, and catched by our QPS stuff, etc.

cc @rafatower @ethervoid

**Comment by rafatower** [comment]
As per Mario's comment in the ticket, that `MAX_RETRIES` affects this:
> Note, this applies only to failed DNS lookups, socket connections and connection timeouts, never to requests where data has made it to the server

The QPS param is in app layer so to say, not network layer. From our side it is used to calculate the delay between requests (exponential backoff) for "app retries" so if we are not 100% accurate with it, I don't think it is big deal. The timeout is by default in a generous amount in seconds.

I wouldn't strive for perfection. What is your concern exactly? what course do you propose?

**Comment by jgoizueta** [comment]
As per our conversation we agree to set the number of (low level) retries to 1.

Summary of our discussion: The low level or network level retries that `requests` handle and are affected by this parameter don't occur for the 429 responses that QPS handles (with exponential backoff retries), so both retry levels (requests/network level vs QPS/app level) are mostly independent.

Having the network level retries will save some cases we're having now of spurious external service timeouts. The only negative effect is that when the external service is down we'll block trying to connect for T*(N+1) seconds where T is the network level [connect timeout](https://github.com/CartoDB/dataservices-api/blob/f716fbb5020e58095a359ea0f98065a9ffcd9dc0/server/lib/python/cartodb_services/cartodb_services/mapzen/geocoder.py#L17) (10s currently) and N the maximum number of retries. So, we'll set N=1 at the moment to fix spurious service problems while being conservative with the maximum blocking time.

**Pull request merged**
