### PR TITLE
[WIP] 4834 add postalcode numeric type function(s)

### PR DESCRIPTION
**Pull request by rafatower**
This PR adds the ability to geocode not only zipcodes expressed as text but the not-so-uncommon numerical zipcodes.

Arguably the DS API client can always cast the column, but this would do it for the client, smoothing integration.

### CODE REVIEW

**Comment by rafatower** [comment]
Now this looks much better:
```
cartodb_dev_user_30e500b9-3b74-49b0-8320-c41bd2a34698_db=> select cdb_geocode_postalcode_point(28045::numeric, 'ESP');
            cdb_geocode_postalcode_point            
----------------------------------------------------
 0101000020E6100000575BB1BFEC9E0DC05A643BDF4F354440
(1 row)

cartodb_dev_user_30e500b9-3b74-49b0-8320-c41bd2a34698_db=> select cdb_geocode_postalcode_point(28045::double precision, 'ESP');
            cdb_geocode_postalcode_point            
----------------------------------------------------
 0101000020E6100000575BB1BFEC9E0DC05A643BDF4F354440
(1 row)
```

What's remaining:
- there are some tests broken, unrelated to this feature
- there's the missing code to upgrade/downgrade the extensions (both client and server), that I'd do as part of the release procedure in master.

@jgoizueta do you mind taking a look? please check the original request to have more context

**Comment by rafatower** [comment]
retest this, please

**Comment by rafatower** [comment]
here's the failing test diff (logging into jenkins machine):
```
$ head -20 /home/ubuntu/workspace/CartoDB-DATASERVICES-API-PR-testing/server/extension/test/regression.diffs
*** /home/ubuntu/workspace/CartoDB-DATASERVICES-API-PR-testing/server/extension/test/expected/00_install_test.out       2017-07-07 16:55:14.935071542 +0000
--- /home/ubuntu/workspace/CartoDB-DATASERVICES-API-PR-testing/server/extension/test/results/00_install_test.out        2017-07-07 16:55:25.619067866 +0000
***************
*** 6,11 ****
--- 6,18 ----
  CREATE EXTENSION cdb_geocoder;
  -- Install the extension
  CREATE EXTENSION cdb_dataservices_server;
+ ERROR:  function cdb_dataservices_server.cdb_geocode_postalcode_point(text, text, text) does not exist
+ LINE 2:   SELECT cdb_dataservices_server.cdb_geocode_postalcode_poin...
+                  ^
+ HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
+ QUERY:  
+   SELECT cdb_dataservices_server.cdb_geocode_postalcode_point(username, orgname, code::text);
+ 
  -- Mock the redis server connection to point to this very test db
  SELECT cartodb.cdb_conf_setconf('redis_metrics_config', '{"redis_host": "localhost", "redis_port": 6379, "timeout": 0.1, "redis_db": 5}');
   cdb_conf_setconf 

======================================================================
```

it is something related to the installation of the extension, but I cannot reproduce it in local.

@jgoizueta most likely it's a silly problem, @dgaubert would have to take over and he'd most likely need a quick hand with at least the release and deploy part.

**Comment by rafatower** [comment]
Now it is a different issue with the client:
```
ubuntu@test24:~$ head -40 /home/ubuntu/workspace/CartoDB-DATASERVICES-API-PR-testing/client/test/regression.diffs
*** /home/ubuntu/workspace/CartoDB-DATASERVICES-API-PR-testing/client/test/expected/10_admin0_test.out  2017-07-07 17:04:34.562884489 +0000
--- /home/ubuntu/workspace/CartoDB-DATASERVICES-API-PR-testing/client/test/results/10_admin0_test.out   2017-07-07 17:04:55.450877715 +0000
***************
*** 11,18 ****
  -- Exercise the public and the proxied function
  SELECT cdb_geocode_admin0_polygon('Spain');
  NOTICE:  cdb_dataservices_client._cdb_geocode_admin0_polygon(3): [contrib_regression] REMOTE NOTICE: cdb_dataservices_server.cdb_geocode_admin0_polygon invoked with params (test_user, <NULL>, Spain)
- CONTEXT:  SQL statement "SELECT cdb_dataservices_client._cdb_geocode_admin0_polygon(username, orgname, country_name)"
- PL/pgSQL function cdb_geocode_admin0_polygon(text) line 16 at SQL statement
   cdb_geocode_admin0_polygon 
  ----------------------------
   
--- 11,16 ----

======================================================================

*** /home/ubuntu/workspace/CartoDB-DATASERVICES-API-PR-testing/client/test/expected/20_admin1_test.out  2017-07-07 17:04:34.562884489 +0000
--- /home/ubuntu/workspace/CartoDB-DATASERVICES-API-PR-testing/client/test/results/20_admin1_test.out   2017-07-07 17:04:55.546877684 +0000
***************
*** 18,25 ****
  -- Exercise the public and the proxied function
  SELECT cdb_geocode_admin1_polygon('California');
  NOTICE:  cdb_dataservices_client._cdb_geocode_admin1_polygon(3): [contrib_regression] REMOTE NOTICE: cdb_dataservices_server.cdb_geocode_admin1_polygon invoked with params (test_user, <NULL>, California)
- CONTEXT:  SQL statement "SELECT cdb_dataservices_client._cdb_geocode_admin1_polygon(username, orgname, admin1_name)"
- PL/pgSQL function cdb_geocode_admin1_polygon(text) line 16 at SQL statement
   cdb_geocode_admin1_polygon 
  ----------------------------
   
--- 18,23 ----
***************
*** 27,34 ****
  
  SELECT cdb_geocode_admin1_polygon('California', 'United States');
  NOTICE:  cdb_dataservices_client._cdb_geocode_admin1_polygon(4): [contrib_regression] REMOTE NOTICE: cdb_dataservices_server.cdb_geocode_admin1_polygon invoked with params (test_user, <NULL>, California, United States)
- CONTEXT:  SQL statement "SELECT cdb_dataservices_client._cdb_geocode_admin1_polygon(username, orgname, admin1_name, country_name)"
- PL/pgSQL function cdb_geocode_admin1_polygon(text,text) line 16 at SQL statement
   cdb_geocode_admin1_polygon 
  ----------------------------
   
--- 25,30 ----
```

**Comment by jgoizueta** [comment]
@dgaubert if you need help I can assist you with deploying this. On the other hand you might decide this should be better fixed in camshaft.

**Comment by dgaubert** [comment]
Hey @jgoizueta, I'm going to need your expertise in data-services' world to be able to deploy this 😄 . I'm reading the whole thread and 👁  the code.

**Comment by jgoizueta** [comment]
By the way, I cherry-picked that last commit because I thought that would fix the tests but that wasn't the case 😞

**Comment by dgaubert** [comment]
Hey @jgoizueta 

I've been reading code and docs and being honest it is still a black box for me. I will need your guidance to be able to deploy it.

But before that, tests are failing and we cannot continue, can we?

**Comment by jgoizueta** [comment]
Well, it seems that now only one test is failing, `100_data_observatory_test` which should be unrelated to these changes. But I'd be nice to fix it to be sure. I'll take a look.

**Pull request merged**
