### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by albertoac**
Do not merge till we publish PR[ #740](https://github.com/CartoDB/developers/pull/740) in the dev center

### CODE REVIEW

**Review by antoniocarlon — APPROVED** [review]
LGTM! :rocket:

**Comment by VictorVelarde** [comment]
@antoniocarlon I stumbled upon this, and I saw a typo on both Phython --> Python

**Comment by antoniocarlon** [comment]
Thank you @VictorVelarde ! :facepalm: Fixing it here https://github.com/CartoDB/dataservices-api/pull/608

**Comment by albertoac** [comment]
Good catch @VictorVelarde ! Is now fixed in #607

**Pull request merged**
