### PR TITLE
add qps_retry to tomtom bulk API calls

### PR DESCRIPTION
**Pull request by alrocar**
Related https://github.com/CartoDB/support/issues/2185

I'm asking our TomTom repr. to know if the GET request to the batch API to get the results is also rate limited, for now I assume it is.

### CODE REVIEW

**Comment by alrocar** [comment]
Summoning @antoniocarlon for CR, although I'm not sure the reason of CI failing... 🙏

**Comment by antoniocarlon** [comment]
The `dataservices-api PR testing / dataservices-api (12) (push)` is failing because dataservices-api is still not working with PG12. I'm asking for help for the other failure.

**Comment by antoniocarlon** [comment]
retest this please

**Comment by ibrahimmenem** [comment]
retest this please

**Comment by antoniocarlon** [comment]
retest this please

**Comment by dgaubert** [comment]
With the following change:

```diff
$ git diff tomtom_bulk_qps_retry..dgaubert/tomtom_bulk_qps_retry
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
index 09bf19f..8f0dba1 100644
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,6 +47,10 @@ jobs:
         run: docker-compose -f docker-compose.yaml exec -T postgres-server bash -c "cd /dataservices-api/server/extension/ && sudo make clean all install installcheck"
         timeout-minutes: 5

+      - name: Show failing tests
+        if: failure()
+        run: docker-compose -f docker-compose.yaml exec -T postgres-server bash -c "cat /dataservices-api/server/extension/test/regression.diffs"
+
       - name: Run client tests
         run: docker-compose -f docker-compose.yaml exec -T postgres-server bash -c "sudo createuser publicuser --no-createrole --no-createdb --no-superuser -U postgres && cd /dataservices-api/client/ && sudo make clean all install installcheck"
         timeout-minutes: 5
```

I've been able to see what's happening with the failing CI job:

```diff
diff -U3 /dataservices-api/server/extension/test/expected/00_install_test.out /dataservices-api/server/extension/test/results/00_install_test.out
--- /dataservices-api/server/extension/test/expected/00_install_test.out	2020-03-04 17:37:42.774027218 +0000
+++ /dataservices-api/server/extension/test/results/00_install_test.out	2020-03-04 17:39:50.042707929 +0000
@@ -3,66 +3,55 @@
 -- Install dependencies
 CREATE EXTENSION postgis;
 CREATE EXTENSION plpythonu;
+ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/plpythonu.control": No such file or directory
 CREATE EXTENSION plproxy;
 CREATE EXTENSION cartodb;
+ERROR:  required extension "plpython3u" is not installed
+HINT:  Use CREATE EXTENSION ... CASCADE to install required extensions too.
 CREATE EXTENSION cdb_geocoder;
+ERROR:  required extension "cartodb" is not installed
+HINT:  Use CREATE EXTENSION ... CASCADE to install required extensions too.
 -- Install the extension
 CREATE EXTENSION cdb_dataservices_server;
+ERROR:  required extension "plpythonu" is not installed
+HINT:  Use CREATE EXTENSION ... CASCADE to install required extensions too.
[...]
```

@alrocar or @antoniocarlon, do you want me to open a PR with this change to be able the output of the results while testing? Also, any clue why this job is not able to create neither `plpythonu` or `plpython3u` extensions?

**Comment by dgaubert** [comment]
I'm planning to deploy it today. Any advice is more than welcome.

**Comment by dgaubert** [comment]
cc/ @rafatower ^^

**Comment by alrocar** [comment]
> @alrocar or @antoniocarlon, do you want me to open a PR with this change to be able the output of the results while testing?

I'm fine with that :)

**Comment by rafatower** [comment]
@dgaubert is it related to this PR https://github.com/CartoDB/dataservices-api/pull/585 superseded by this other PR https://github.com/CartoDB/dataservices-api/pull/584 ?

**Comment by dgaubert** [comment]
I've just synced development with this branch to get the CI working. The PR tries to solve https://github.com/CartoDB/support/issues/2185 and https://github.com/CartoDB/support/issues/2415

**Pull request merged**
