### PR TITLE
:fire: Data Observatory

### PR DESCRIPTION
**Pull request by Jesus89**
This PR aims to remove everything related to Data Observatory v1 from the server and client of Data Services API.

It's the first time I contribute to this repo, so I invoke help from the reviewers to make sure everything is well done :sweat_smile:

NOTE: this can not be merged/deployed until March 31st

### CODE REVIEW

**Review by Algunenano — CHANGES_REQUESTED** [review]
Some notes:
* 0.39.3--0.39.4.sql file needs to contain the changes done (the delete calls to the functions).
* 0.39.4--0.39.3.sql needs to do the opposite (create the functions) so a rollback is possible.
* The geocodio tests are failing, apparently due to some precision issues. I would reduce the precision from 3 to 2 decimal places and move on.

And a question: Do we have/want to remove anything from the client sql extension?

**Comment by Jesus89** [comment]
Thanks. I just did make release NEW_VERSION=0.39.4, so those files were generated automatically. I'll check that

**Comment by Algunenano** [comment]
> Thanks. I just did make release NEW_VERSION=0.39.4, so those files were generated automatically. I'll check that

They are generated empty automatically, but we need to edit them before the release.

**Comment by Jesus89** [comment]
Ready for a second review. Summary:
- Remove _Data Observatory_ from client 0.31.0
- Remove _Data Observatory_ from server 0.40.0
- Remove _Data Observatory_ from python lib 0.24.0

**Review by Algunenano — APPROVED** [review]
I'm not sure if the revokes are necessary, but it looks good.

**Comment by Jesus89** [comment]
Thanks for the review :)

> I'm not sure if the revokes are necessary, but it looks good.

Yep, I thought the same because we are dropping those functions, but just in case.

**Comment by rafatower** [comment]
@ManuelLR and @jvillarf to be aware of stuff that may affect config changes

**Pull request merged**
